version: "2"
services:
    ss-server:
        image: shadowsocks/shadowsocks-libev
        ports:
            - "8443:8388/tcp"
            - "8443:8388/udp"
        restart: always
        environment:
          METHOD: 'aes-256-cfb'
          PASSWORD: 'your_password'
    kcp-server:
        image: spidertifa/kcp-server:20190109
        ports:
            - "443:38081/udp"
        restart: always
        depends_on:
            - ss-server
        command: ./server_linux_amd64 -t "ss-server:8388" -l ":38081" -mode fast2 --key 'your_password' --crypt aes-128
